# This workflow is triggered by the dispatch workflow.

on:
  repository_dispatch:
    types: [ copy-workflow ]

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg: ${{ github.event.client_payload.targets }}
    env:
      TEMPLATE_REPO_DIR: "template-repo"
      TEMPLATE_DIR: "templates"
      NEEDS_UPDATE: 0
    name: Update ${{ matrix.cfg.target }}
    steps:
    - name: Checkout ${{ matrix.cfg.target }}
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.cfg.target }}
        token: ${{ secrets.WEB3BOT_GITHUB_TOKEN }}
        persist-credentials: true
    - name: Checkout template repository
      uses: actions/checkout@v2
      with:
        path: ${{ env.TEMPLATE_REPO_DIR }}
    - name: Create commits
      run: |
        git config user.name web3-bot
        git config user.email "web3-bot@users.noreply.github.com"
        for f in $(jq -r ".[]" <<< '${{ toJson(github.event.client_payload.files) }}'); do 
          echo -e "\nProcessing $f."
          # add DO NOT EDIT header
          tmp=$(mktemp)
          cat $TEMPLATE_REPO_DIR/$TEMPLATE_DIR/header.yml $TEMPLATE_REPO_DIR/$TEMPLATE_DIR/$f > $tmp
          mv $tmp $TEMPLATE_REPO_DIR/$TEMPLATE_DIR/$f
          # create commit, if necessary
          commit_msg=""
          if [[ ! -f "$f" ]]; then
            echo "First deployment.\n"
            commit_msg="add $f"
          else
            status=$(cmp --silent $f $TEMPLATE_REPO_DIR/$TEMPLATE_DIR/$f; echo $?)
            if [[ $status -ne 0 ]]; then
              echo "Update needed."
              commit_msg="update $f"
            else
              echo "File identical. Skipping."
              continue
            fi
          fi
          dir=$(dirname $f)
          mkdir -p $dir
          cp $TEMPLATE_REPO_DIR/$TEMPLATE_DIR/$f $dir
          git add $f
          git commit -m "$commit_msg"
          echo "NEEDS_UPDATE=1" >> $GITHUB_ENV
        done
        rm -rf $TEMPLATE_REPO_DIR
    - name: Create Pull Request
      if: ${{ env.NEEDS_UPDATE == 1 }}
      uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8 #v3.8.2
      with:
        title: "sync: ${{ github.event.client_payload.github_event.pull_request.title }}"
        body: |
          Change introduced by ${{ github.event.client_payload.github_event.pull_request.html_url }}.
          ---
          You can trigger a rebase by commenting `@web3-bot rebase`.
        token: ${{ secrets.WEB3BOT_GITHUB_TOKEN }}
        committer: web3-bot <web3-bot@users.noreply.github.com>
        author: web3-bot <web3-bot@users.noreply.github.com>
        branch: web3-bot/sync
        delete-branch: true
