on:
  pull_request:
    branches: [ master ]
    types: [ closed ] # IMPORTANT: check the merge status for every job: github.event.pull_request.merged == true

jobs:
  matrix:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          TARGETS=$(jq -c . .github/workflows/config.json)
          echo "::set-output name=targets::$TARGETS"
  copy:
    if: github.event.pull_request.merged == true
    needs: [ matrix ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.targets) }}
        workflow: [ "autorebase", "automerge", "go-test", "go-check" ]
    env:
      WORKFLOW_DIR: "workflow-repo"
      FILE: "${{ matrix.workflow }}.yml"
      NEEDS_UPDATE: 0
    name: Update ${{ matrix.workflow }} on ${{ matrix.cfg.target }}
    steps:
    - name: Checkout ${{ matrix.cfg.target }}
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.cfg.target }}
        token: ${{ secrets.IPLDBOT_GITHUB_TOKEN }}
        persist-credentials: true
    - name: Checkout workflow templates
      uses: actions/checkout@v2
      with:
        path: ${{ env.WORKFLOW_DIR }}
    - name: Add "DO NOT EDIT" header to ${{ env.FILE }}
      run: |
        tmp=$(mktemp)
        cat $WORKFLOW_DIR/workflow-templates/header.yml $WORKFLOW_DIR/workflow-templates/$FILE > $tmp
        mv $tmp $WORKFLOW_DIR/workflow-templates/$FILE
    - name: Check if an update to ${{ env.FILE }} is neccessary
      run: |
        STATUS=$(cmp --silent .github/workflows/$FILE $WORKFLOW_DIR/workflow-templates/$FILE; echo $?)
        if [[ $STATUS -ne 0 ]]; then
          echo "Update needed."
          echo "NEEDS_UPDATE=1" >> $GITHUB_ENV
        else
          echo "Files indentical. Skipping."
        fi
    - name: Copy ${{ env.FILE }} to target repo
      if: ${{ env.NEEDS_UPDATE == 1 }}
      run: |
        mkdir -p .github/workflows/
        cp $WORKFLOW_DIR/workflow-templates/$FILE .github/workflows/
        rm -rf $WORKFLOW_DIR
    - name: Create Pull Request
      if: ${{ env.NEEDS_UPDATE == 1 }}
      uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8 #v3.8.2
      with:
        commit-message: "update ${{ env.FILE }}: ${{ github.event.pull_request.title }}"
        title: "${{ matrix.workflow }}: ${{ github.event.pull_request.title }}"
        body: |
          Change introduced by ${{ github.event.pull_request.html_url }}.

          ---
          You can trigger a rebase by commenting `@ipldbot rebase`.
        token: ${{ secrets.IPLDBOT_GITHUB_TOKEN }}
        committer: ipldbot <ipldbot@users.noreply.github.com>
        author: ipldbot <ipldbot@users.noreply.github.com>
        branch: ipldbot/update-${{matrix.workflow }}
        delete-branch: true
