# Trigger the execution of copy-workflow.yml, in batches of 8 repositories.
# This workflow is needed since GitHub Actions limits the matrix size to 256 jobs.
# We use one job per repository per file.

on:
  push:
    branches: [ master ]

env:
  # We could use a higher number here. We use a small number just to make sure to create multiple batches.
  MAX_REPOS_PER_WORKFLOW: 8
  FILES: '[ ".github/workflows/automerge.yml", ".github/workflows/go-test.yml", ".github/workflows/go-check.yml" ]' # a JSON array of the files to distribute

jobs:
  matrix:
    name: Trigger copy workflows
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-matrix.outputs.targets }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          TARGETS=$(jq '. | _nwise(${{ env.MAX_REPOS_PER_WORKFLOW }})' config.json | jq -sc '. | to_entries')
          echo "::set-output name=targets::$TARGETS"
  dispatch:
    needs: [ matrix ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.targets) }}
    name: Start copy workflow (batch ${{ matrix.cfg.key }})
    steps:
      - uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4 # v1.1.3
        with:
          token: ${{ secrets.WEB3BOT_GITHUB_TOKEN }}
          event-type: copy-workflow
          client-payload: '{ "github_event": ${{ toJson(github.event) }}, "files": ${{ env.FILES }}, "targets": ${{ toJson(matrix.cfg.value) }} }'
