name: Releaser
on: [ workflow_call ]

jobs:
  releaser:
    runs-on: ubuntu-latest
    env:
      VERSION: ""
    steps:
      - uses: actions/checkout@v2
      - name: Determine version
        run: echo "VERSION=$(jq -r .version version.json)" >> $GITHUB_ENV
      - name: Create release
        run: |
          git fetch origin --tags
          if ! $(git rev-list ${{ env.VERSION}}.. &> /dev/null); then
            git tag ${{ env.VERSION }}
            git push --tags
          fi
